### PR TITLE
Fixed the typo (coloe -> color) in util.ts

### PR DESCRIPTION
**Pull request by vyPal**
Ok I fixed it in this file instead.

### CODE REVIEW

**Review by gamertike — CHANGES_REQUESTED** [review]
Please run `yarn docs` in your terminal so that these changes take effect in the docs. In the future i can insure there will be a workflow for this to do it for you.

**Comment by gamertike** [comment]
> Ok I fixed it in this file instead.

If you would like, i can do this for you while giving credit to you for spotting this typo.

**Comment by vyPal** [comment]
You can do it if you want, I'd do it, but I won't be able to get to a device that can handle typescript for about 10 hours, so if you want to wait, I'll do it in the morning, if not, you can do it yourself

**Comment by gamertike** [comment]
> You can do it if you want, I'd do it, but I won't be able to get to a device that can handle typescript for about 10 hours, so if you want to wait, I'll do it in the morning, if not, you can do it yourself

Ill do it since im working on an update rn anyway. Thank you for contributing! Can i close this pr?

**Pull request closed without merging**
